"""
Validate blog figures by re-generating them and computing pixel diff.

For each figure, re-runs the original generation command and compares
pixel-wise to the published blog version.

Tolerance: figures are flagged if mean absolute pixel diff > THRESHOLD
(0-1 scale, where 1 = max difference). Matplotlib rendering is not
perfectly bit-identical across runs, so we use a loose threshold of ~0.01
(1% average deviation), which catches actual data changes vs. font/AA noise.

Usage:
    uv run python analyze/validate_figures.py
    uv run python analyze/validate_figures.py --threshold 0.01
"""

import argparse
import os
import subprocess
import sys
import tempfile

import numpy as np
from PIL import Image

BASE = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BLOG_DIR = os.path.expanduser("~/axu.sh/public/attention-residuals")

# Quicksort prompt used throughout the routing analysis scripts
QUICKSORT = (
    "def quicksort(arr):\\n"
    "    if len(arr) <= 1:\\n"
    "        return arr\\n"
    "    pivot = arr[len(arr) // 2]\\n"
    "    left = [x for x in arr if x < pivot]"
)

# Each entry: figure filename, regeneration command (run from BASE), known_bad flag
FIGURES = [
    {
        "name": "per-token-code.png",
        "known_bad": True,
        "reason": "Block4 routing collapsed in all saved checkpoints; unknown source checkpoint",
        "cmd": None,
    },
    {
        "name": "og-training-dynamics.png",
        "known_bad": False,
        "reason": "Reference image from AttnRes paper, not generated by us",
        "cmd": None,
        "skip": True,
    },
    {
        "name": "boundary-analysis-annotated.png",
        "known_bad": False,
        "reason": "From adaptive boundary experiment (separate wandb run), not main checkpoints",
        "cmd": "uv run python analyze/plot_boundary_annotated.py",
        # saves to fixed path relative to BASE (no {out} or {outdir} in command)
        "absolute_output": os.path.join(BASE, "analyze/wandb_data/plots/boundary_analysis_annotated.png"),
    },
    {
        "name": "depth-attention-heatmap-block.png",
        "cmd": (
            "uv run python analyze/plot_depth_heatmaps.py"
            " --input figures/v2/alphas_block.npz"
            " --output {out}"
            " --title 'Block AttnRes v2 — Depth Attention Weights'"
            " --prefix B"
        ),
    },
    {
        "name": "depth-attention-heatmap.png",
        "cmd": (
            "uv run python analyze/plot_depth_heatmaps.py"
            " --input figures/v2/alphas_full.npz"
            " --output {out}"
            " --title 'Full AttnRes v2 — Depth Attention Weights'"
            " --prefix L"
        ),
    },
    {
        "name": "depth-heatmap-value-residual.png",
        "cmd": (
            "uv run python analyze/plot_depth_heatmaps.py"
            " --input figures/v2/alphas_value_residual.npz"
            " --output {out}"
            " --title 'Block AttnRes + Value Residual — Depth Attention'"
            " --prefix B"
        ),
    },
    {
        "name": "query-vector-cosine-similarity-block.png",
        "cmd": (
            "uv run python analyze/plot_query_vectors.py"
            " --ckpt data/v2/block_attnres/ckpt.pt"
            " --output-dir {outdir}"
            " --label-prefix B"
        ),
        "output_in": "query_cosine_block_attnres.png",
    },
    {
        "name": "query-vector-cosine-similarity.png",
        "cmd": (
            "uv run python analyze/plot_query_vectors.py"
            " --ckpt data/v2/full_attnres/ckpt.pt"
            " --output-dir {outdir}"
            " --label-prefix L"
        ),
        "output_in": "query_cosine_full_attnres.png",
    },
    {
        "name": "training-dynamics.png",
        "cmd": (
            "uv run python analyze/plot_dynamics.py"
            " --dynamics-files"
            " baseline:figures/v2/dynamics_baseline.npz"
            " full_attnres:figures/v2/dynamics_full.npz"
            " block_attnres:figures/v2/dynamics_block.npz"
            " --output {out}"
        ),
    },
    {
        "name": "routing-code.png",
        "cmd": (
            "uv run python analyze/plot_token_routing.py"
            " --ckpt data/v2/block_attnres/ckpt.pt"
            " --output-dir {outdir}"
        ),
        # plot_token_routing saves routing_code_block_attnres.png in output-dir
        "output_in": "routing_code_block_attnres.png",
    },
    {
        "name": "routing-by-prompt-type.png",
        "cmd": (
            "uv run python analyze/plot_token_routing.py"
            " --ckpt data/v2/block_attnres/ckpt.pt"
            " --output-dir {outdir}"
        ),
        # plot_token_routing saves routing_comparison_block_attnres.png in output-dir
        "output_in": "routing_comparison_block_attnres.png",
        "shared_cmd_with": "routing-code.png",  # same command, just different output file
    },
]


def img_diff(path_a: str, path_b: str) -> float:
    """Mean absolute pixel diff (0-1 scale) between two images, resized to match."""
    a = np.array(Image.open(path_a).convert("RGB")).astype(np.float32) / 255.0
    b_img = Image.open(path_b).convert("RGB")
    a_img = Image.open(path_a).convert("RGB")
    if a_img.size != b_img.size:
        b_img = b_img.resize(a_img.size, Image.LANCZOS)
    b = np.array(b_img).astype(np.float32) / 255.0
    return float(np.abs(a - b).mean())


def run_cmd(cmd: str, cwd: str) -> tuple[bool, str]:
    """Run shell command. Returns (success, stderr)."""
    result = subprocess.run(
        cmd, shell=True, cwd=cwd, capture_output=True, text=True
    )
    return result.returncode == 0, result.stderr + result.stdout


def check_plot_dynamics_args():
    """Check if plot_dynamics.py accepts the --baseline/--full/--block flags."""
    result = subprocess.run(
        "uv run python analyze/plot_dynamics.py --help",
        shell=True, cwd=BASE, capture_output=True, text=True
    )
    return "--baseline" in result.stdout or "--baseline" in result.stderr


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--threshold", type=float, default=0.01,
                        help="Mean absolute pixel diff threshold to flag as changed (0-1 scale)")
    parser.add_argument("--only", help="Only validate this figure name (substring match)")
    args = parser.parse_args()

    results = []
    tmpdir = tempfile.mkdtemp(prefix="attnres_validate_")
    print(f"Temp output dir: {tmpdir}\n")

    # Track which commands have already been run (for shared commands)
    ran_cmds = {}

    for fig in FIGURES:
        name = fig["name"]
        if args.only and args.only not in name:
            continue

        blog_path = os.path.join(BLOG_DIR, name)

        if not os.path.exists(blog_path):
            results.append((name, "MISSING_BLOG", 0.0, "Blog file not found"))
            continue

        if fig.get("skip"):
            results.append((name, "SKIPPED", 0.0, fig.get("reason", "")))
            continue

        if fig.get("known_bad"):
            results.append((name, "KNOWN_BAD", 0.0, fig.get("reason", "")))
            continue

        cmd_template = fig.get("cmd")
        if not cmd_template:
            results.append((name, "NO_CMD", 0.0, "No regeneration command defined"))
            continue

        # Handle commands that produce multiple output files (routing scripts)
        shared_with = fig.get("shared_cmd_with")
        output_in = fig.get("output_in")

        absolute_output = fig.get("absolute_output")

        if shared_with and shared_with in ran_cmds:
            # Reuse output dir from prior run
            out_path = os.path.join(ran_cmds[shared_with], output_in)
        else:
            fig_tmpdir = os.path.join(tmpdir, name.replace(".png", ""))
            os.makedirs(fig_tmpdir, exist_ok=True)
            out_path = absolute_output or os.path.join(fig_tmpdir, "out.png")

            # Build command with actual paths
            cmd = cmd_template.format(out=out_path, outdir=fig_tmpdir)

            print(f"[{name}] Running: {cmd[:80]}...")
            ok, log = run_cmd(cmd, BASE)
            if not ok:
                results.append((name, "CMD_FAILED", 0.0, log[-300:]))
                continue

            # If output_in is set, the script saved to a specific filename
            if output_in:
                out_path = os.path.join(fig_tmpdir, output_in)
                ran_cmds[name] = fig_tmpdir  # save for shared commands

        if not os.path.exists(out_path):
            results.append((name, "OUTPUT_MISSING", 0.0, f"Expected at {out_path}"))
            continue

        diff = img_diff(blog_path, out_path)
        status = "OK" if diff <= args.threshold else "CHANGED"
        results.append((name, status, diff, out_path))

    # Print results table
    print("\n" + "=" * 80)
    print(f"{'Figure':<45} {'Status':<12} {'PixelDiff':>10}  Notes")
    print("=" * 80)
    for name, status, diff, note in results:
        flag = "✓" if status in ("OK", "SKIPPED", "KNOWN_BAD") else "✗"
        diff_str = f"{diff:.4f}" if diff > 0 else "—"
        note_str = note if status in ("CMD_FAILED", "OUTPUT_MISSING", "KNOWN_BAD", "SKIPPED", "MISSING_BLOG") else ""
        print(f"  {flag}  {name:<43} {status:<12} {diff_str:>10}  {note_str[:50]}")

    n_changed = sum(1 for _, s, _, _ in results if s == "CHANGED")
    n_bad = sum(1 for _, s, _, _ in results if s == "KNOWN_BAD")
    n_ok = sum(1 for _, s, _, _ in results if s == "OK")
    print("=" * 80)
    print(f"\n  {n_ok} OK  |  {n_changed} CHANGED  |  {n_bad} KNOWN BAD\n")

    if n_changed > 0:
        sys.exit(1)


if __name__ == "__main__":
    main()
